name: Deploy to CloudBase

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build
        env:
          VITE_TCB_ENV_ID: ${{ secrets.VITE_TCB_ENV_ID }}

      - name: Deploy to CloudBase
        uses: TencentCloudBase/cloudbase-action@v2
        with:
          secretId: ${{ secrets.TENCENT_SECRET_ID }}
          secretKey: ${{ secrets.TENCENT_SECRET_KEY }}
          envId: ${{ secrets.VITE_TCB_ENV_ID }}
          staticSrcPath: dist
