name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ] # 如果你的主分支叫 master，请修改这里

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build
        env:
          # 这里会读取你刚才在 GitHub Settings 里填的 Secret
          VITE_TCB_ENV_ID: ${{ secrets.VITE_TCB_ENV_ID }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Vue 打包后的目录名
          branch: gh-pages # 部署到这个分支